# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    tarif: 2.5 

services:
    client_service:
        class: AppBundle\Service\ClientService
        arguments: ["@doctrine.orm.entity_manager"]  
        # permet de passer un argument au constructeur de ClientService
        

